// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.communityhelper.feedback;

import java.io.Serializable;

privileged aspect FeedbackPK_Roo_Serializable {
    
    declare parents: FeedbackPK implements Serializable;
    
    private static final long FeedbackPK.serialVersionUID = 1L;
    
}
